-- Picker keymaps (mini.pick + mini.extra; setup lives in config.mini)
local MiniPick = require("mini.pick")
local MiniExtra = require("mini.extra")
local pick = MiniPick.builtin
local extra = MiniExtra.pickers

local nmap_leader = function(suffix, rhs, desc)
	vim.keymap.set("n", "<Leader>" .. suffix, rhs, { desc = desc })
end

nmap_leader("ff", pick.files, "Files")
nmap_leader("fh", pick.help, "Help tags")
nmap_leader(".", pick.resume, "Resume")
nmap_leader("fq", function()
	extra.list({ scope = "quickfix" })
end, "Quickfix")
nmap_leader("fQ", function()
	extra.list({ scope = "location" })
end, "Loclist")
nmap_leader("fd", function()
	extra.diagnostic({ scope = "current" })
end, "Diagnostic buf")
nmap_leader("fD", function()
	extra.diagnostic({ scope = "all" })
end, "Diagnostic workspace")
nmap_leader("fs", function()
	extra.lsp({ scope = "workspace_symbol" })
end, "Symbols workspace")
nmap_leader("fm", function()
	extra.marks()
end, "Marks")
nmap_leader("fr", function()
	extra.registers()
end, "Registers")
nmap_leader("<space>", pick.grep_live, "Grep live")
nmap_leader("/", function()
	extra.buf_lines({ scope = "current" })
end, "Lines")
nmap_leader("fw", function()
	pick.grep({ pattern = vim.fn.expand("<cword>") })
end, "Grep word")
nmap_leader("j/", function()
	extra.history({ scope = "/" })
end, '"/" history')
nmap_leader("j;", function()
	extra.history({ scope = ":" })
end, '":" history')
nmap_leader("k", pick.buffers, "Buffers")

vim.api.nvim_create_autocmd("LspAttach", {
	callback = function(args)
		local function map_buf(lhs, rhs)
			vim.keymap.set("n", lhs, rhs, { buffer = args.buf })
		end
		local lsp_picker = function(scope)
			return function()
				extra.lsp({ scope = scope })
			end
		end

		map_buf("grr", lsp_picker("references"))
		map_buf("gri", lsp_picker("implementation"))
		map_buf("grt", lsp_picker("type_definition"))
		map_buf("gra", vim.lsp.buf.code_action)
		map_buf("gO", lsp_picker("document_symbol"))
		map_buf("gd", lsp_picker("definition"))
		map_buf("gD", lsp_picker("declaration"))
	end,
})
