require("user.plugins")
require("user.options")
require("user.autocmds")
-- require("user.snacks")
require("user.cmp")
require("user.format")
-- require("user.git")
require("user.lsp")
require("user.mini")
require("user.org")
-- require("user.others")
-- require("user.telescope")
